name: Kevin BZzone
title: My Workshop
description: Just my modding portfolio
github: [metadata]
markdown: kramdown
google_analytics: UA-XXXXXXXXX-1
assets:
  autoprefixer:
    browsers:
    - "last 2 versions"
    - "IE > 9"
plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/page/:num/"
future: true
